#ifndef BOARD_CONFIG_H
#define BOARD_CONFIG_H

#define AUDIO_I2S_METHOD_SIMPLEX

#ifdef AUDIO_I2S_METHOD_SIMPLEX

// Microphone Pins
#define AUDIO_I2S_MIC_GPIO_WS   GPIO_NUM_18
#define AUDIO_I2S_MIC_GPIO_SCK  GPIO_NUM_19
#define AUDIO_I2S_MIC_GPIO_DIN  GPIO_NUM_23

// Speaker Output Disabled
#define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_NC
#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_NC
#define AUDIO_I2S_SPK_GPIO_LRCK GPIO_NUM_NC

#endif

// Buttons & Built-in LED Pins
#define BOOT_BUTTON_GPIO        GPIO_NUM_0
#define TOUCH_BUTTON_GPIO       GPIO_NUM_5
#define ASR_BUTTON_GPIO         GPIO_NUM_13
#define BUILTIN_LED_GPIO        GPIO_NUM_2

// Display Pin
#define DISPLAY_SDA_PIN         GPIO_NUM_21

#endif // BOARD_CONFIG_H
